### ISSUE TITLE
[RESTAPI] Erro na validação de Schema na atualização de documentos de um Bundle

### ISSUE THREAD

**Issue by patymori** [scieloorg/kernel#221]
### Descrição do problema
Durante atualização de documentos de um `Bundle` utilizando o OPAC-Airflow, o Kernel retornou erro HTTP 500:

**Log do erro no OPAC-Airflow**:
```
[2020-07-03 20:00:36,363] {logging_mixin.py:95} INFO - [[34m2020-07-03 20:00:36,363[0m] {[34mdocs_utils.py:[0m256} INFO[0m - Updating Bundle "[1m0104-0707-2020-v29[0m" with Documents: [1m[{'id': 'xfxKrk3RxLGjS9sWxY9LgLH', 'order': '00203'}][0m[0m
[2020-07-03 20:00:36,369] {logging_mixin.py:95} INFO - [[34m2020-07-03 20:00:36,368[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: kernel_conn. Host: 192.168.169.12, Port: 6543, Schema: http, Login: None, Password: None, extra: {}[0m[0m
[2020-07-03 20:00:36,369] {logging_mixin.py:95} INFO - [[34m2020-07-03 20:00:36,369[0m] {[34mhttp_hook.py:[0m131} INFO[0m - Sending '[1mPUT[0m' to url: [1mhttp://192.168.169.12:6543/bundles/0104-0707-2020-v29/documents[0m[0m
[2020-07-03 20:00:36,414] {taskinstance.py:1047} ERROR - 500 Server Error: Internal Server Error for url: http://192.168.169.12:6543/bundles/0104-0707-2020-v29/documents
Traceback (most recent call last):
  File "/home/scielo/spf/opac-airflow/.venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/scielo/spf/opac-airflow/.venv/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 158, in execute
    condition = super(ShortCircuitOperator, self).execute(context)
  File "/home/scielo/spf/opac-airflow/.venv/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/scielo/spf/opac-airflow/.venv/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/scielo/spf/opac-airflow/airflow/dags/sync_documents_to_kernel.py", line 143, in link_documents_to_documentsbundle
    _sps_package, documents, issn_index_json_path
  File "/home/scielo/spf/opac-airflow/airflow/dags/operations/sync_documents_to_kernel_operations.py", line 347, in link_documents_to_documentsbundle
    response = update_documents_in_bundle(bundle_id, payload)
  File "/home/scielo/spf/opac-airflow/airflow/dags/operations/docs_utils.py", line 262, in update_documents_in_bundle
    raise LinkDocumentToDocumentsBundleException(str(exc)) from None
operations.exceptions.LinkDocumentToDocumentsBundleException: 500 Server Error: Internal Server Error for url: http://192.168.169.12:6543/bundles/0104-0707-2020-v29/documents

```

**Log do erro no Kernel**:
```
2020-07-03 20:00:36,391 ERROR [waitress][waitress] Exception while serving /bundles/0104-0707-2020-v29/documents
Traceback (most recent call last):
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/waitress/channel.py", line 349, in service
    task.service()
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/waitress/task.py", line 439, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/sentry_sdk/integrations/pyramid.py", line 123, in sentry_patched_wsgi_call
    environ, start_response
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 127, in __call__
    reraise(*_capture_exception(hub))
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 124, in __call__
    partial(_sentry_start_response, start_response, span),
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/sentry_sdk/integrations/pyramid.py", line 120, in sentry_patched_inner_wsgi_call
    reraise(*einfo)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/sentry_sdk/integrations/pyramid.py", line 116, in sentry_patched_inner_wsgi_call
    return old_wsgi_call(self, environ, start_response)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/sentry_sdk/integrations/pyramid.py", line 90, in sentry_patched_invoke_exception_view
    rv = old_invoke_exception_view(self, *args, **kwargs)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/view.py", line 771, in invoke_exception_view
    reraise_(*exc_info)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/compat.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/home/scielo/spf/kernel/.venv/src/scielo-kernel/documentstore/pyramid_prometheus.py", line 37, in tween
    response = handler(request)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/sentry_sdk/integrations/pyramid.py", line 90, in sentry_patched_invoke_exception_view
    rv = old_invoke_exception_view(self, *args, **kwargs)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/view.py", line 767, in invoke_exception_view
    request_iface=request_iface.combined,
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/viewderivers.py", line 384, in authdebug_view
    return view(context, request)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/sentry_sdk/integrations/pyramid.py", line 81, in sentry_patched_handle_request
    return old_handle_request(self, request, *args, **kwargs)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/config/views.py", line 169, in __call__
    return view(context, request)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/config/views.py", line 188, in attr_view
    return view(context, request)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
    return view(context, request)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/viewderivers.py", line 384, in authdebug_view
    return view(context, request)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
    result = view(context, request)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
    response = view(request)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/cornice/service.py", line 493, in wrapper
    validator(request, **args)
  File "/home/scielo/spf/kernel/.venv/lib/python3.7/site-packages/cornice/validators/_colander.py", line 49, in _validator
    raise TypeError("Schema should inherit from "
TypeError: Schema should inherit from colander.MappingSchema.
```

### Passos para reproduzir o problema
1. Registre/atualize documentos de um `Bundle` no Kernel com, ao menos, os metadados de um documento, utilizando o endpoint REST API `/bundles/<ID do Bundle>/documents`. Ex:
```json
[{"id": "QuaquerPidV3", "order": "00003"}]
```
2. Observe o erro reportado acima

### Comportamento esperado
O bundle deve ser atualizado com sucesso.

### Screenshots ou vídeos
N/A

### Anexos
N/A

### Ambiente utilizado
O erro foi detectado durante testes de validação para a migração na máquina de DSTeste com o Kernel e o OPAC-Airflow da branch `master`.

**Comment by patymori** [comment]
Foi detectado que com a atualização do Cornice para a versão 4.x, a forma como o validador é utilizado precisa ser alterada. Detalhes em https://cornice.readthedocs.io/en/latest/upgrading.html#x-to-4-x
